<a href="https://colab.research.google.com/github/Karsuman4298/Deep-learning/blob/main/Pytorch_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#The torch.nn.Module is the fundamental base class for all neural network modules in PyTorch, providing the building blocks and essential functionality for creating and managing network architectures.

#Key Functions and Features
Base Class for Models and Layers: Both entire neural networks and individual layers (like nn.Linear or nn.Conv2d) are subclasses of nn.Module. This allows for a nested, modular structure for building complex architectures.


#Parameter Management:

 Subclassing nn.Module aut#omatically tracks all learnable parameters (weights and biases) defined within the model, making them accessible via the .parameters() method.
 Forward Pass Definition: You must override the forward(self, x) method to define how input data x flows through the network's layers and computations.

#Device Management:
It provides convenient methods like .to(device) to easily move the entire model and its parameters between the CPU and GPU (CUDA).


#Integration with Autograd:
 nn.Module works seamlessly with PyTorch's automatic differentiation engine (autograd), which computes gradients for parameters during backpropagation.
Standardized Workflow: It enables the use of standard training loop steps such as model.zero_grad(), loss.backward(), and optimizer.step().

#Serialization:
 Modules are easy to save and restore, which is essential for checkpoints and model deployment.


In [1]:
import torch
import torch.nn as nn

In [28]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.Relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out=self.linear1(features)
    out=self.Relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)

    return out

In [29]:
features=torch.rand(10,5)
model=Model(num_features=5)
model(features)

tensor([[0.4274],
        [0.4144],
        [0.4185],
        [0.4287],
        [0.4140],
        [0.4173],
        [0.4209],
        [0.4257],
        [0.4113],
        [0.4196]], grad_fn=<SigmoidBackward0>)

In [30]:
model=Model(num_features=5)
model(features)

tensor([[0.5214],
        [0.5152],
        [0.4918],
        [0.5341],
        [0.5052],
        [0.5039],
        [0.5018],
        [0.5103],
        [0.5047],
        [0.4880]], grad_fn=<SigmoidBackward0>)

In [32]:
model.linear1.weight

Parameter containing:
tensor([[ 0.3893, -0.3520, -0.2068, -0.4377,  0.0058],
        [ 0.0651,  0.2548, -0.0861, -0.4396, -0.3415],
        [ 0.0733,  0.1600,  0.0595,  0.3028, -0.3226]], requires_grad=True)

In [33]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3898, -0.0686,  0.2629]], requires_grad=True)

In [34]:
model.linear1.bias

Parameter containing:
tensor([0.3589, 0.1698, 0.2016], requires_grad=True)

In [35]:
model.linear2.bias

Parameter containing:
tensor([-0.0960], requires_grad=True)

In [20]:
!pip install torchinfo

# torchinfo -> to vizualize our network

In [36]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# nn.Sequential

In [38]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__(self,num_features)
    self.network=nn.Sequential(
          linear1 = nn.Linear(num_features,3),
          Relu = nn.ReLU(),
          linear2 = nn.Linear(3,1),
          sigmoid = nn.Sigmoid()
    )




  def forward(self,features):
    out=self.network(features)


    return out