<a href="https://colab.research.google.com/github/Karsuman4298/Practice-machine-learning-/blob/main/PYtorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [17]:
tensor= torch.tensor([[5,7],
                       [6,6],
                           ])

In [18]:
tensor

tensor([[5, 7],
        [6, 6]])

In [19]:
tensor.shape

torch.Size([2, 2])

In [20]:
tensor.ndim

2

random tensors

In [51]:
random_tensors= torch.rand(3,2)
print(random_tensors)

tensor([[0.8759, 0.5451],
        [0.4735, 0.1416],
        [0.6166, 0.1036]])


In [41]:
random_tensors.ndim

2

  Random tensors to size of an image

In [50]:
rand_tensor_img= torch.rand(size=(224,224,3))

rand_tensor_img.shape, rand_tensor_img.ndim

(torch.Size([224, 224, 3]), 3)

In [78]:
range=torch.arange(1,11)
range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
ten_zeros=torch.zeros_like(range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
print("hiii")

hiii
