<a href="https://colab.research.google.com/github/Karsuman4298/Deep-learning/blob/main/PYtorch(tensors_manipulation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning pytorch

In [51]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [52]:
tensor= torch.tensor([[5,7],
                       [6,6],
                           ])

In [53]:
tensor

tensor([[5, 7],
        [6, 6]])

In [54]:
tensor.shape

torch.Size([2, 2])

In [55]:
tensor.ndim

2

random tensors

In [56]:
random_tensors= torch.rand(3,2)
print(random_tensors)

tensor([[0.4050, 0.1602],
        [0.5313, 0.0965],
        [0.3997, 0.6162]])


In [57]:
random_tensors.ndim

2

  Random tensors to size of an image

In [58]:
rand_tensor_img= torch.rand(size=(224,224,3))

rand_tensor_img.shape, rand_tensor_img.ndim

(torch.Size([224, 224, 3]), 3)

In [59]:
range=torch.arange(1,11)
range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
ten_zeros=torch.zeros_like(range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
print("hiii")

hiii


In [62]:
##mul=float_16_tensor*float_32_tensor

In [63]:
##mul.dtype

In [64]:
some_tensor=torch.rand(3,3)

In [65]:
print(some_tensor)
print(f"datatype of the tensor: {some_tensor.dtype}")
print(f"shape of the tensor: {some_tensor.shape}")

tensor([[0.4702, 0.5731, 0.5789],
        [0.9754, 0.7679, 0.2289],
        [0.0623, 0.0795, 0.6060]])
datatype of the tensor: torch.float32
shape of the tensor: torch.Size([3, 3])


Tensor operations


In [66]:
tensor= torch.tensor([1,2,3])



In [67]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [68]:
print(tensor,"*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [69]:
%%time
torch.matmul(tensor,tensor)


CPU times: user 308 µs, sys: 707 µs, total: 1.02 ms
Wall time: 13 ms


tensor(14)

Shape errors

In [70]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.2665, 0.0877],
        [0.7241, 0.2562]])

In [71]:
tensor_a=torch.tensor([[2,2],
                       [2,3],
                       [7,5]])
tensor_b=torch.tensor([[3,5],
                       [7,5],
                       [9,8]])

Transpose

In [72]:
tensor_a.T

tensor([[2, 2, 7],
        [2, 3, 5]])

In [73]:
tensor_b

tensor([[3, 5],
        [7, 5],
        [9, 8]])

In [74]:
%%time
print(f" The matrix multiplication is \n :{tensor_a.T @tensor_b}")


 The matrix multiplication is 
 :tensor([[83, 76],
        [72, 65]])
CPU times: user 1.12 ms, sys: 21 µs, total: 1.14 ms
Wall time: 6.57 ms


Tensor aggregation

In [75]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [76]:
x.min()

tensor(0)

In [77]:
x.max()

tensor(90)

torch.mean() requires a tensor of float32 datatypes

In [78]:
torch.mean(x.type(torch.float32))

tensor(45.)

argmax -> returns the position of the maximum value in the tensor

argmin-> minimun of a tensor

In [79]:
torch.argmin(x)

tensor(0)

Reshaping - reshapes an input to a defined shape

View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

Stacking - combine multiple tensors on of each other(vstack) or side by(hstack).

Squeeze - revomes all '1' dimension from a tensor,

Unsqueeze- add a '1' dimension to a target tensor.

permute - Return a view of the input with dimensions permuted (swapped) in a certain



In [80]:
import torch
x= torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [81]:
##adds an extra dimensions
x_reshaped= x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [96]:
import torch
x=torch.arange(1,11)
x,x.size()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [99]:
x_reshaped=x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [105]:
z=x_reshaped.view(1,10)
z

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

## Changing z changes x because a view of a tensor shares same memory as the original input.

In [110]:
z[:,0]=5
z,x

(tensor([[ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10]))

In [124]:
## stack tensors on the top each other
x_stacked=torch.stack([x,x,x],dim=0)
x_stacked,x_stacked.size()

(tensor([[ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10],
         [ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10],
         [ 5,  2,  3,  4,  5,  5,  7,  8,  9, 10]]),
 torch.Size([3, 10]))

In [133]:
## torhc.squeeze() -> remoe=ve all single dimention from the targeted vector.
x=torch.arange(1,11)
x,x.shape


(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [132]:
y=x.squeeze()
y.shape

torch.Size([10])

In [134]:
## torch.permute -> rearrange the dimension of the target in a specific order.
x_original=torch.rand(size=(224,224,3))
x_permuted=x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

Indexing

In [135]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [147]:
x[0][2][2]

tensor(9)