<a href="https://colab.research.google.com/github/Karsuman4298/Deep-learning/blob/main/PYtorch(Fundamentals).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning pytorch

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [4]:
tensor= torch.tensor([[5,7],
                       [6,6],
                           ])

In [5]:
tensor

tensor([[5, 7],
        [6, 6]])

In [6]:
tensor.shape

torch.Size([2, 2])

In [7]:
tensor.ndim

2

random tensors

In [8]:
random_tensors= torch.rand(3,2)
print(random_tensors)

tensor([[0.8376, 0.9500],
        [0.7097, 0.4890],
        [0.4715, 0.2760]])


In [9]:
random_tensors.ndim

2

  Random tensors to size of an image

In [10]:
rand_tensor_img= torch.rand(size=(224,224,3))

rand_tensor_img.shape, rand_tensor_img.ndim

(torch.Size([224, 224, 3]), 3)

In [11]:
range=torch.arange(1,11)
range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
ten_zeros=torch.zeros_like(range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
print("hiii")

hiii


In [14]:
##mul=float_16_tensor*float_32_tensor

In [15]:
##mul.dtype

In [16]:
some_tensor=torch.rand(3,3)

In [17]:
print(some_tensor)
print(f"datatype of the tensor: {some_tensor.dtype}")
print(f"shape of the tensor: {some_tensor.shape}")

tensor([[0.5871, 0.0541, 0.8275],
        [0.4761, 0.2886, 0.8290],
        [0.7336, 0.9066, 0.7551]])
datatype of the tensor: torch.float32
shape of the tensor: torch.Size([3, 3])


Tensor operations


In [18]:
tensor= torch.tensor([1,2,3])



In [19]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [20]:
print(tensor,"*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [21]:
%%time
torch.matmul(tensor,tensor)


CPU times: user 412 µs, sys: 76 µs, total: 488 µs
Wall time: 8.64 ms


tensor(14)

Shape errors

In [22]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.2239, 0.4287],
        [1.0739, 0.2819]])

In [23]:
tensor_a=torch.tensor([[2,2],
                       [2,3],
                       [7,5]])
tensor_b=torch.tensor([[3,5],
                       [7,5],
                       [9,8]])

Transpose

In [24]:
tensor_a.T

tensor([[2, 2, 7],
        [2, 3, 5]])

In [25]:
tensor_b

tensor([[3, 5],
        [7, 5],
        [9, 8]])

In [26]:
%%time
print(f" The matrix multiplication is \n :{tensor_a.T @tensor_b}")


 The matrix multiplication is 
 :tensor([[83, 76],
        [72, 65]])
CPU times: user 665 µs, sys: 0 ns, total: 665 µs
Wall time: 5.29 ms


Tensor aggregation

In [27]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
x.min()

tensor(0)

In [29]:
x.max()

tensor(90)

torch.mean() requires a tensor of float32 datatypes

In [30]:
torch.mean(x.type(torch.float32))

tensor(45.)

argmax -> returns the position of the maximum value in the tensor

argmin-> minimun of a tensor

In [31]:
torch.argmin(x)

tensor(0)

Reshaping - reshapes an input to a defined shape

View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

Stacking - combine multiple tensors on of each other(vstack) or side by(hstack).

Squeeze - revomes all '1' dimension from a tensor,

Unsqueeze- add a '1' dimension to a target tensor.

permute - Return a view of the input with dimensions permuted (swapped) in a certain



In [32]:
import torch
x= torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [33]:
##adds an extra dimensions
x_reshaped= x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [34]:
import torch
x=torch.arange(1,11)
x,x.size()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [35]:
x_reshaped=x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [36]:
z=x_reshaped.view(1,10)
z

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

## Changing z changes x because a view of a tensor shares same memory as the original input.

In [37]:
z[:,0]=5
z,x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [38]:
## stack tensors on the top each other
x_stacked=torch.stack([x,x,x],dim=0)
x_stacked,x_stacked.size()

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 torch.Size([3, 10]))

In [39]:
## torhc.squeeze() -> remoe=ve all single dimention from the targeted vector.
x=torch.arange(1,11)
x,x.shape


(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [40]:
y=x.squeeze()
y.shape

torch.Size([10])

In [41]:
## torch.permute -> rearrange the dimension of the target in a specific order.
x_original=torch.rand(size=(224,224,3))
x_permuted=x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

Indexing

In [42]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [43]:
x[0][2][2]

tensor(9)

Numpy

In [44]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
array, array.dtype


(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

In [45]:
array=array+1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [48]:
tensor=torch.ones(7)
add=tensor+1
add

tensor([2., 2., 2., 2., 2., 2., 2.])

**Reproductibility**
to reduce the randomness in neural network and pytorch comes the concept of a **Random seed**.





In [53]:
import torch
rand_tensor_A=torch.rand(3,4)
rand_tensor_B=torch.rand(3,4)
print(rand_tensor_A)
print(rand_tensor_B)
print(rand_tensor_A==rand_tensor_B)


tensor([[0.3073, 0.9699, 0.0460, 0.6907],
        [0.2987, 0.4948, 0.9712, 0.7291],
        [0.0677, 0.4965, 0.7156, 0.9921]])
tensor([[0.6726, 0.4178, 0.4704, 0.7365],
        [0.9557, 0.8837, 0.5361, 0.9537],
        [0.6391, 0.2598, 0.6676, 0.6122]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [61]:
##making random but reproducible tensors
import torch
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
rand_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand_tensor_D=torch.rand(3,4)
print(rand_tensor_C)
print(rand_tensor_D )
print(rand_tensor_C==rand_tensor_D)




tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [64]:
import torch
torch.cuda.is_available()


True

In [65]:
##Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [67]:
tensor=torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [69]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Numpy cant work on gpu thats why we are getting error , we need to move the tensor yo cpu for further computation**

In [72]:
tensor_on_cpu=tensor_on_gpu.cpu()
tensor_on_cpu

tensor([1, 2, 3])