<a href="https://colab.research.google.com/github/Karsuman4298/Deep-learning/blob/main/PYtorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
tensor= torch.tensor([[5,7],
                       [6,6],
                           ])

In [3]:
tensor

tensor([[5, 7],
        [6, 6]])

In [4]:
tensor.shape

torch.Size([2, 2])

In [5]:
tensor.ndim

2

random tensors

In [6]:
random_tensors= torch.rand(3,2)
print(random_tensors)

tensor([[0.8116, 0.1895],
        [0.8156, 0.4680],
        [0.3935, 0.2287]])


In [7]:
random_tensors.ndim

2

  Random tensors to size of an image

In [8]:
rand_tensor_img= torch.rand(size=(224,224,3))

rand_tensor_img.shape, rand_tensor_img.ndim

(torch.Size([224, 224, 3]), 3)

In [9]:
range=torch.arange(1,11)
range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
ten_zeros=torch.zeros_like(range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
print("hiii")

hiii


In [23]:
float_32_tensor= torch.tensor([2.0,3.0,4.0,5.0],dtype=torch.int32,device=
                              'cuda',requires_grad=False)

In [25]:
float_32_tensor.dtype


torch.int32

In [26]:
float_16_tensor= float_32_tensor.type(torch.float)

In [28]:
mul=float_16_tensor*float_32_tensor

In [29]:
mul.dtype

torch.float32

In [30]:
some_tensor=torch.rand(3,3)

In [35]:
print(some_tensor)
print(f"datatype of the tensor: {some_tensor.dtype}")
print(f"shape of the tensor: {some_tensor.shape}")

tensor([[0.7093, 0.0719, 0.0864],
        [0.6672, 0.8138, 0.2210],
        [0.0048, 0.5584, 0.5477]])
datatype of the tensor: torch.float32
shape of the tensor: torch.Size([3, 3])


Tensor operations


In [48]:
tensor= torch.tensor([1,2,3])



In [49]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [52]:
print(tensor,"*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [55]:
%%time
torch.matmul(tensor,tensor)


CPU times: user 111 µs, sys: 7 µs, total: 118 µs
Wall time: 122 µs


tensor(14)

Shape errors

In [65]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.9472, 0.8446],
        [0.9849, 1.0412]])

In [73]:
tensor_a=torch.tensor([[2,2],
                       [2,3],
                       [7,5]])
tensor_b=torch.tensor([[3,5],
                       [7,5],
                       [9,8]])

Transpose

In [78]:
tensor_a.T

tensor([[2, 2, 7],
        [2, 3, 5]])

In [77]:
tensor_b

tensor([[3, 5],
        [7, 5],
        [9, 8]])

In [82]:
%%time
print(f" The matrix multiplication is \n :{tensor_a.T @tensor_b}")


 The matrix multiplication is 
 :tensor([[83, 76],
        [72, 65]])
CPU times: user 816 µs, sys: 0 ns, total: 816 µs
Wall time: 822 µs


Tensor aggregation

In [99]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
x.min()

tensor(0)

In [87]:
x.max()

tensor(90)

torch.mean() requires a tensor of float32 datatypes

In [96]:
torch.mean(x.type(torch.float32))

tensor(45.)

argmax -> returns the position of the maximum value in the tensor

argmin-> minimun of a tensor

In [103]:
torch.argmin(x)

tensor(0)